### ISSUE TITLE
error: ValueError: Filter must not be larger than the input: Filter: (2, 2) Input: (1, 112)

### ISSUE THREAD

**Issue by caseybasichis** [tobyfrancis/VGG16-Image-Feature-Mapping#1]
Hi,

I'm excited to get started with your repo, but I'm getting an error:

Using TensorFlow backend.
Loading Images...
Done.
Loading Model...
Traceback (most recent call last):
  File "image_map.py", line 184, in <module>
    tsne()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "image_map.py", line 65, in tsne
    model = vggmodel(vgg_weights)
  File "/Users/caseybasichis/Prog/audio_repos/VGG16-Image-Feature-Mapping/scripts/VGG_keras.py", line 20, in vggmodel
    model.add(MaxPooling2D((2,2), strides=(2,2)))
  File "/usr/local/lib/python3.5/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 514, in **call**
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python3.5/site-packages/keras/layers/pooling.py", line 162, in call
    dim_ordering=self.dim_ordering)
  File "/usr/local/lib/python3.5/site-packages/keras/layers/pooling.py", line 212, in _pooling_function
    border_mode, dim_ordering, pool_mode='max')
  File "/usr/local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1701, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 536, in max_pool
    name=name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1038, in _max_pool
    data_format=data_format, name=name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/common_shapes.py", line 505, in max_pool_shape
    padding)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/common_shapes.py", line 184, in get2d_conv_output_size
    (row_stride, col_stride), padding_type)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/common_shapes.py", line 149, in get_conv_output_size
    "Filter: %r Input: %r" % (filter_size, input_size))
ValueError: Filter must not be larger than the input: Filter: (2, 2) Input: (1, 112)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x11b149668>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 171, in **del**
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 167, in close
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in **enter**
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 452, in raise_exception_on_not_ok_status
UnboundLocalError: local variable 'status' referenced before assignment

**Comment by caseybasichis** [comment]
I think I made it a bit further but I'm hitting another error I can't seem to get around:

I imported import keras.optimizers and modified:
sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
sgd = keras.optimizers.SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
based on some google research.

Using TensorFlow backend.
Loading Images...
Done.
Loading Model...
Model loaded.
Done.
Performing forward pass through VGG Net...
Traceback (most recent call last):
  File "image_map.py", line 186, in <module>
    tsne()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "image_map.py", line 76, in tsne
    features = model.predict(images)
  File "/usr/local/lib/python3.5/site-packages/keras/models.py", line 671, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/training.py", line 1161, in predict
    check_batch_dim=False)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/training.py", line 97, in standardize_input_data
    str(array.shape))
Exception: Error when checking : expected zeropadding2d_input_1 to have 4 dimensions, but got array with shape (0, 1)

**Comment by tobyfrancis** [comment]
Hey Casey! That's a common problem with loading weights in Keras, the formatting for the weights is inconsistent - where did you get your VGG16 weights? If you want I can upload mine - the code works for me.

**Comment by tobyfrancis** [comment]
Oh actually the problem is that your input into the first layer (zeropadding is the first layer before convolution) is of the wrong shape. Tell me about the image database you're working with! My code automatically crops all images to the VGG dimensions (3x224x224 - if the image is grayscale it's converted to RGB). If you're interested, I was going to rewrite the code for variable image sizes - essentially, you can't use Fully Connected Layers on variable image sizes because there's a pre-determined number of weights. If I write this code, it'll be using Fisher-Vector or some other kind of encoding on the final convolution outputs. 

Also, the GPU code was written for usage with Theano - Theano works faster with GPU. If you're using Tensorflow, make sure to set it to CPU mode.

**Comment by acidrainpsu1980** [comment]
I can't not load your weight. Could you upload your weight again?
